"""Write docs/data_report.md (+ figures) from the artifacts the pipeline actually produced.

python -m s2a.data.report
"""

from __future__ import annotations

import gzip
import json
import statistics
from collections import Counter
from collections.abc import Sequence
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import yaml

from s2a.data.build_dataset import CONFIG, SPLITS, out_root
from s2a.data.render import render_ink, save_grid
from s2a.paths import REPO_ROOT, data_root
from s2a.spec import canonical_json
from s2a.spec.tokens import load_tokenizers, per_screen_texts

DOCS = REPO_ROOT / "docs"
FIG = DOCS / "figures"


def _node_types(n: dict[str, Any], c: Counter[str]) -> None:
    c[n["t"]] += 1
    for k in n.get("c", []):
        _node_types(k, c)
    if "item" in n:
        _node_types(n["item"], c)


def _leaves(n: dict[str, Any]) -> int:
    kids = n.get("c") or ([n["item"]] if "item" in n else [])
    return sum(_leaves(k) for k in kids) if kids else 1


def _pct(values: Sequence[float], q: float) -> float:
    return float(np.percentile(values, q)) if values else float("nan")


def _hist(values: Sequence[float], title: str, xlabel: str, path: Path, line: float | None = None) -> None:
    fig, ax = plt.subplots(figsize=(6, 3.2), dpi=120)
    ax.hist(values, bins=40, color="#4f5bd5")
    if line is not None:
        ax.axvline(line, color="#d62728", linestyle="--", label=f"target {line:g}")
        ax.legend()
    ax.set_title(title)
    ax.set_xlabel(xlabel)
    ax.set_ylabel("count")
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)


def main() -> None:
    FIG.mkdir(parents=True, exist_ok=True)
    cfg = yaml.safe_load(CONFIG.read_text(encoding="utf-8"))
    conv = json.loads((data_root() / "rico_specs" / "stats.json").read_text(encoding="utf-8"))
    synth = json.loads((out_root() / "stats.json").read_text(encoding="utf-8"))
    specs = [
        json.loads(line)["spec"]
        for line in (data_root() / "rico_specs" / "specs.jsonl").open(encoding="utf-8")
    ]

    leaves = [_leaves(s["screens"][0]["body"]) for s in specs]
    types: Counter[str] = Counter()
    for s in specs:
        _node_types(s["screens"][0]["body"], types)
        for slot in ("appbar", "bottomnav", "fab"):
            if slot in s["screens"][0]:
                types[slot] += 1
    tok = load_tokenizers()["gemma-4-E2B-it"]
    rng = np.random.default_rng(0)
    sample_idx = rng.choice(len(specs), size=min(5000, len(specs)), replace=False)
    tokens = [
        len(tok.encode(per_screen_texts(specs[i])[0], add_special_tokens=False).ids) for i in sample_idx
    ]
    _hist(leaves, "Elements per converted RICO screen", "elements", FIG / "elements_per_screen.png")
    _hist(
        tokens,
        "Spec tokens per screen (Gemma 4 tokenizer)",
        "tokens",
        FIG / "tokens_per_screen.png",
        line=250,
    )

    # Sample grids and stroke-class counts from the first train shard.
    first = sorted((out_root() / "train").glob("shard_*.jsonl.gz"))[0]
    imgs = []
    cls_counts: Counter[str] = Counter()
    with gzip.open(first, "rt", encoding="utf-8") as f:
        for k, line in enumerate(f):
            rec = json.loads(line)
            cls_counts.update(rec["stroke_cls"])
            if k < 16:
                imgs.append(render_ink(rec["ink"], rec["stroke_cls"], 384))
    save_grid(imgs, FIG / "synthetic_samples.png", cols=4)

    lines = [
        "# Data report",
        "",
        "Generated by `python -m s2a.data.report` from the pipeline's own outputs; "
        "nothing here is hand-edited.",
        "",
        "## 1. RICO -> UI specs",
        "",
        f"Source: RICO semantic annotations, {conv['source_screens']:,} screens "
        "(JSON hierarchies only, no screenshots).",
        "",
        "| Outcome | Screens |",
        "|---|---:|",
        *[f"| {k} | {v:,} |" for k, v in conv["reasons"].items()],
        "",
        "Kept screens satisfy: portrait, no drawer/modal overlay, mostly Latin text (ML Kit reads en-US), "
        "3-30 sketchable elements, valid against the schema after conversion.",
        "",
        f"Elements per kept screen: median {statistics.median(leaves):.0f}, p10 {_pct(leaves, 10):.0f}, "
        f"p90 {_pct(leaves, 90):.0f}.",
        "",
        f"Spec size (canonical JSON, Gemma 4 tokenizer, {len(tokens):,} random screens): median "
        f"**{statistics.median(tokens):.0f}** tokens/screen, p90 {_pct(tokens, 90):.0f}, max {max(tokens)} "
        f"(target: median < 250). ![tokens](figures/tokens_per_screen.png)",
        "",
        "Node types in converted specs:",
        "",
        "| Type | Count |",
        "|---|---:|",
        *[f"| {k} | {v:,} |" for k, v in types.most_common()],
        "",
        "## 2. Splits (by app)",
        "",
        "Apps are assigned to train/val/test by a hash of the package name, so no app appears in two splits.",
        "",
        "| Split | Apps | Specs | Samples | 1 screen | 2 screens | 3 screens | Failed "
        "| Strokes/sample (median, p90) |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---|",
    ]
    for s in SPLITS:
        st = synth[s]
        sp = st.get("strokes_per_sample", {})
        lines.append(
            f"| {s} | {st['apps']:,} | {st['specs']:,} | {st.get('ok', 0):,} | {st.get('screens_1', 0):,} | "
            f"{st.get('screens_2', 0):,} | {st.get('screens_3', 0):,} | {st.get('failed', 0):,} | "
            f"{sp.get('median', 0):.0f}, {sp.get('p90', 0):.0f} |"
        )
    train_types = synth["train"]["element_types"]
    total_cls = sum(cls_counts.values())
    lines += [
        "",
        "## 3. Synthetic sketches",
        "",
        "Every sample is laid out by our own randomised layout (not the app's pixels) and drawn per the "
        "sketch legend, so sketch and gold spec always agree. Noise model (configs/data.yaml):",
        "",
        "| Parameter | Range |",
        "|---|---|",
        *[f"| pen.{k} | {v} |" for k, v in cfg["pen"].items()],
        *[f"| transform.{k} | {v} |" for k, v in cfg["transform"].items()],
        f"| order.shuffled_prob | {cfg['order']['shuffled_prob']} |",
        f"| canvas.drawn_frame_prob | {cfg['canvas']['drawn_frame_prob']} |",
        f"| layout.list_mark_prob | {cfg['layout']['list_mark_prob']} |",
        f"| multiscreen.share | {cfg['multiscreen']['share']} |",
        *[f"| augment.{k} | {v} |" for k, v in cfg["augment"].items()],
        "",
        "Element types in the train split:",
        "",
        "| Element | Count |",
        "|---|---:|",
        *[f"| {k} | {v:,} |" for k, v in train_types.items()],
        "",
        f"Stroke classes in the first train shard ({total_cls:,} strokes): "
        + ", ".join(f"{k} {v / total_cls:.1%}" for k, v in cls_counts.most_common())
        + ".",
        "",
        "Random training samples (shape strokes black, handwriting blue, arrows red, drawn frames grey):",
        "",
        "![samples](figures/synthetic_samples.png)",
        "",
        "![elements](figures/elements_per_screen.png)",
        "",
        "## 4. Example converted spec",
        "",
        "```json",
        canonical_json(specs[int(sample_idx[0])]),
        "```",
        "",
    ]
    (DOCS / "data_report.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {DOCS / 'data_report.md'}")


if __name__ == "__main__":
    main()
