// Regenerates derived Dart sources. Run after editing lib/spec/material_icons.dart or
// lib/render/sketch_widgets.dart:   dart run tool/gen.dart
// test/generated_files_test.dart fails if the checked-in outputs are stale.
import 'dart:io';

import 'package:sketch2app/spec/material_icons.dart';

const iconsOut = 'lib/render/icons.g.dart';
const widgetsSourceIn = 'lib/render/sketch_widgets.dart';
const widgetsSourceOut = 'lib/export/sketch_widgets_source.g.dart';

String iconsSource() {
  final b = StringBuffer()
    ..writeln(
      '// GENERATED by tool/gen.dart from lib/spec/material_icons.dart. Do not edit.',
    )
    ..writeln("import 'package:flutter/material.dart';")
    ..writeln()
    ..writeln('const Map<String, IconData> specIcons = {');
  for (final e in materialIconIds.entries) {
    b.writeln("  '${e.key}': Icons.${e.value},");
  }
  b.writeln('};');
  return b.toString();
}

String widgetsSourceConstant(String source) {
  if (source.contains("'''")) {
    throw StateError('sketch_widgets.dart must not contain triple quotes');
  }
  return '// GENERATED by tool/gen.dart from lib/render/sketch_widgets.dart. Do not edit.\n'
      '// ignore_for_file: unnecessary_raw_strings\n\n'
      '/// Verbatim copy of lib/render/sketch_widgets.dart, written into every exported project.\n'
      "const String sketchWidgetsSource = r'''\n$source''';\n";
}

void main() {
  File(iconsOut).writeAsStringSync(iconsSource());
  final source = File(
    widgetsSourceIn,
  ).readAsStringSync().replaceAll('\r\n', '\n');
  File(widgetsSourceOut).writeAsStringSync(widgetsSourceConstant(source));
  stdout.writeln('wrote $iconsOut and $widgetsSourceOut');
}
