/// Android platform folder for exported projects, captured from `flutter create --platforms android` on
/// Flutter 3.44.0 and trimmed to text files.
///
/// Binary files are deliberately absent: the Gradle wrapper jar and scripts are regenerated by the
/// Flutter tool on first build (the template's own android/.gitignore excludes them), and the PNG
/// launcher icons are replaced by a vector drawable. Placeholders: {{appName}}, {{applicationId}}.
library;

Map<String, String> androidFiles({
  required String appName,
  required String applicationId,
}) {
  final kotlinDir = applicationId.replaceAll('.', '/');
  String fill(String t) => t
      .replaceAll('{{appName}}', _xmlEscape(appName))
      .replaceAll('{{applicationId}}', applicationId);
  return {
    'android/.gitignore': _gitignore,
    'android/build.gradle.kts': _rootGradle,
    'android/settings.gradle.kts': _settingsGradle,
    'android/gradle.properties': _gradleProperties,
    'android/gradle/wrapper/gradle-wrapper.properties': _wrapperProperties,
    'android/app/build.gradle.kts': fill(_appGradle),
    'android/app/src/main/AndroidManifest.xml': fill(_mainManifest),
    'android/app/src/debug/AndroidManifest.xml': _internetManifest,
    'android/app/src/profile/AndroidManifest.xml': _internetManifest,
    'android/app/src/main/kotlin/$kotlinDir/MainActivity.kt': fill(
      _mainActivity,
    ),
    'android/app/src/main/res/drawable/launch_background.xml':
        _launchBackground('@android:color/white'),
    'android/app/src/main/res/drawable-v21/launch_background.xml':
        _launchBackground('?android:colorBackground'),
    'android/app/src/main/res/drawable/ic_launcher.xml': _launcherIcon,
    'android/app/src/main/res/values/styles.xml': _styles('Light'),
    'android/app/src/main/res/values-night/styles.xml': _styles('Black'),
  };
}

String _xmlEscape(String s) => s
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');

const _gitignore = '''gradle-wrapper.jar
/.gradle
/captures/
/gradlew
/gradlew.bat
/local.properties
GeneratedPluginRegistrant.java
.cxx/

# Remember to never publicly share your keystore.
key.properties
**/*.keystore
**/*.jks
''';

const _rootGradle = '''allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

val newBuildDir: Directory =
    rootProject.layout.buildDirectory
        .dir("../../build")
        .get()
rootProject.layout.buildDirectory.value(newBuildDir)

subprojects {
    val newSubprojectBuildDir: Directory = newBuildDir.dir(project.name)
    project.layout.buildDirectory.value(newSubprojectBuildDir)
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register<Delete>("clean") {
    delete(rootProject.layout.buildDirectory)
}
''';

const _settingsGradle = r'''pluginManagement {
    val flutterSdkPath =
        run {
            val properties = java.util.Properties()
            file("local.properties").inputStream().use { properties.load(it) }
            val flutterSdkPath = properties.getProperty("flutter.sdk")
            require(flutterSdkPath != null) { "flutter.sdk not set in local.properties" }
            flutterSdkPath
        }

    includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("dev.flutter.flutter-plugin-loader") version "1.0.0"
    id("com.android.application") version "9.0.1" apply false
    id("org.jetbrains.kotlin.android") version "2.3.20" apply false
}

include(":app")
''';

const _gradleProperties =
    '''org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false
''';

const _wrapperProperties = r'''distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-9.1.0-all.zip
''';

const _appGradle = '''plugins {
    id("com.android.application")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

android {
    namespace = "{{applicationId}}"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    defaultConfig {
        applicationId = "{{applicationId}}"
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    buildTypes {
        release {
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig = signingConfigs.getByName("debug")
        }
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

flutter {
    source = "../.."
}
''';

const _mainManifest =
    r'''<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application
        android:label="{{appName}}"
        android:name="${applicationName}"
        android:icon="@drawable/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:taskAffinity=""
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
    <queries>
        <intent>
            <action android:name="android.intent.action.PROCESS_TEXT"/>
            <data android:mimeType="text/plain"/>
        </intent>
    </queries>
</manifest>
''';

const _internetManifest =
    '''<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <!-- Lets the Flutter tool talk to the app for hot reload and debugging. -->
    <uses-permission android:name="android.permission.INTERNET"/>
</manifest>
''';

const _mainActivity = '''package {{applicationId}}

import io.flutter.embedding.android.FlutterActivity

class MainActivity : FlutterActivity()
''';

String _launchBackground(String color) =>
    '''<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="$color" />
</layer-list>
''';

const _launcherIcon = '''<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="48dp"
    android:height="48dp"
    android:viewportWidth="48"
    android:viewportHeight="48">
    <path android:fillColor="#3F51B5" android:pathData="M8,4h32a4,4 0 0 1 4,4v32a4,4 0 0 1 -4,4h-32a4,4 0 0 1 -4,-4v-32a4,4 0 0 1 4,-4z" />
    <path android:fillColor="#FFFFFF" android:pathData="M14,12h20v4h-20z M14,20h20v12h-20z M14,36h9v3h-9z" />
</vector>
''';

String _styles(String base) =>
    '''<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="LaunchTheme" parent="@android:style/Theme.$base.NoTitleBar">
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
    <style name="NormalTheme" parent="@android:style/Theme.$base.NoTitleBar">
        <item name="android:windowBackground">?android:colorBackground</item>
    </style>
</resources>
''';
