/// Spec -> complete Flutter project as a path -> content map. Pure Dart and deterministic: the same spec
/// and options always give byte-identical files, so exports can be tested, diffed and cached.
library;

import 'dart:collection';

import '../spec/spec.dart';
import 'android_template.dart';
import 'code.dart';
import 'screen_codegen.dart';
import 'sketch_widgets_source.g.dart';

class ExportOptions {
  const ExportOptions({
    this.appName = 'Sketch App',
    this.packageName = 'sketch_app',
    this.org = 'com.example',
  });

  final String appName;

  /// Dart package name (lowercase_with_underscores).
  final String packageName;
  final String org;

  String get applicationId => '$org.$packageName';
}

/// Every generated file, sorted by path.
SplayTreeMap<String, String> exportProject(
  AppSpec spec, {
  ExportOptions options = const ExportOptions(),
}) {
  final files = SplayTreeMap<String, String>();
  final codegen = ScreenCodegen(spec);
  for (final screen in spec.screens) {
    files['lib/screens/${screenFileName(screen.id)}'] = _screenFile(
      codegen,
      screen,
    );
  }
  files['lib/main.dart'] = _mainFile(spec, options);
  files['lib/sketch_widgets.dart'] = sketchWidgetsSource;
  files['test/widget_test.dart'] = _widgetTest(spec, options);
  files['pubspec.yaml'] = _pubspec(options);
  files['analysis_options.yaml'] = _analysisOptions;
  files['.gitignore'] = _gitignore;
  files['README.md'] = _readme(spec, options);
  files['ui_spec.json'] = '${canonicalJson(spec)}\n';
  files.addAll(
    androidFiles(
      appName: options.appName,
      applicationId: options.applicationId,
    ),
  );
  return files;
}

String _screenFile(ScreenCodegen codegen, ScreenSpec screen) {
  codegen.usedHelpers.clear();
  final body = printCode(codegen.scaffold(screen), indent: 4, col: 11, tail: 1);
  final cls = screenClassName(screen.id);
  final helpersImport = codegen.usedHelpers.isEmpty
      ? ''
      : "\nimport '../sketch_widgets.dart';\n";
  return '''import 'package:flutter/material.dart';
$helpersImport
class $cls extends StatelessWidget {
  const $cls({super.key});

  @override
  Widget build(BuildContext context) {
    return $body;
  }
}
''';
}

String _mainFile(AppSpec spec, ExportOptions options) {
  final imports = [
    for (final s in spec.screens) "import 'screens/${screenFileName(s.id)}';",
  ]..sort();
  final routes = [
    for (final s in spec.screens)
      '        ${str(routeName(spec, s.id)).text}: (context) => const ${screenClassName(s.id)}(),',
  ];
  return '''import 'package:flutter/material.dart';

${imports.join('\n')}
import 'sketch_widgets.dart';

void main() => runApp(const SketchApp());

class SketchApp extends StatelessWidget {
  const SketchApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: ${str(options.appName).text},
      theme: sketchTheme(),
      routes: {
${routes.join('\n')}
      },
    );
  }
}
''';
}

String _widgetTest(AppSpec spec, ExportOptions options) {
  final first = spec.screens.first;
  return '''import 'package:flutter_test/flutter_test.dart';
import 'package:${options.packageName}/main.dart';
import 'package:${options.packageName}/screens/${screenFileName(first.id)}';

void main() {
  testWidgets('app opens on the first screen', (tester) async {
    await tester.pumpWidget(const SketchApp());
    expect(find.byType(${screenClassName(first.id)}), findsOneWidget);
  });
}
''';
}

String _pubspec(ExportOptions options) => '''name: ${options.packageName}
description: "Generated by Sketch2App from a hand-drawn sketch."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
''';

/// Stricter than the default template on purpose: generated code is fully const-correct.
const _analysisOptions = '''include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_single_quotes
''';

const _gitignore = '''.dart_tool/
.flutter-plugins-dependencies
.pub-cache/
.pub/
/build/
/coverage/
*.iml
.idea/
/android/app/debug
/android/app/profile
/android/app/release
''';

String _readme(AppSpec spec, ExportOptions options) {
  final screens = [
    for (final s in spec.screens)
      '- `${routeName(spec, s.id)}` ${s.title} (`lib/screens/${screenFileName(s.id)}`)',
  ];
  return '''# ${options.appName}

Generated by Sketch2App from a hand-drawn sketch. `ui_spec.json` is the spec it was generated from.

## Run

```bash
flutter pub get
flutter run
```

Only the Android platform folder is included. To add others: `flutter create --platforms=ios,web .`

## Screens

${screens.join('\n')}
''';
}
